=== anweiss/OSCAL/build/metaschema/lib/metaschema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
  xmlns:oscal="http://csrc.nist.gov/ns/oscal/1.0"
  xmlns:m="http://csrc.nist.gov/ns/oscal/metaschema/1.0"
  targetNamespace="http://csrc.nist.gov/ns/oscal/metaschema/1.0">

  <!-- Import any OSCAL schemas needed for samples... -->
  <!--<xs:import namespace="http://csrc.nist.gov/ns/oscal/1.0"
    schemaLocation="../../../schema/xml/oscal-catalog-schema.xsd"/>-->
  <xs:element name="METASCHEMA">
    <xs:complexType>
      
      <xs:sequence>
        <xs:element ref="m:schema-name"/>
        <xs:element ref="m:short-name"/>
        <xs:element ref="m:namespace" minOccurs="1"/>
        <xs:element ref="m:remarks" minOccurs="0"/>
        <xs:element ref="m:import"  minOccurs="0" maxOccurs="unbounded"/>
        <xs:choice maxOccurs="unbounded">
          <xs:element ref="m:define-assembly"/>
          <xs:element ref="m:define-field"/>
          <xs:element ref="m:define-flag"/>
        </xs:choice>
      </xs:sequence>
      <xs:attribute name="root" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="define-assembly">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="m:flag"/>
        <xs:element minOccurs="0" ref="m:formal-name"/>
        <xs:element minOccurs="0" ref="m:description"/>
        <xs:element minOccurs="0" ref="m:remarks"/>

        <xs:element name="model" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element ref="m:assembly"/>
                <xs:element ref="m:assemblies"/>
                <xs:element ref="m:field"/>
                <xs:element ref="m:fields"/>
                <xs:element ref="m:choice"/>
                <xs:element ref="m:prose"/>
              </xs:choice>
              <xs:element ref="m:any" minOccurs="0"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>

        <xs:element minOccurs="0" maxOccurs="unbounded" ref="m:example"/>
      </xs:sequence>
      <xs:attribute name="address" type="xs:NCName"/>
      <xs:attribute name="group-as" type="xs:NCName"/>
      <xs:attribute name="name" use="required" type="xs:NCName"/>
      <xs:attribute name="show-docs"/>
      <xs:attribute name="acquire-from" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="define-field">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="m:flag"/>
        <xs:element minOccurs="0" ref="m:formal-name"/>
        <xs:element minOccurs="0" ref="m:description"/>
        <xs:element minOccurs="0" ref="m:remarks"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="m:example"/>
      </xs:sequence>
      <xs:attribute name="as">
        
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:enumeration value="boolean" />
              <xs:enumeration value="empty" />
              <xs:enumeration value="string" />
              <xs:enumeration value="mixed" />
            </xs:restriction>
          </xs:simpleType>
        
      </xs:attribute>
      <xs:attribute name="group-as" type="xs:NCName"/>
      <xs:attribute name="name" use="required" type="xs:NCName"/>
      <xs:attribute name="show-docs"/>
      <xs:attribute name="acquire-from" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="define-flag">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" ref="m:formal-name"/>
        <xs:element minOccurs="0" ref="m:description"/>
        <xs:element minOccurs="0" ref="m:remarks"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="m:example"/>
      </xs:sequence>
      <xs:attribute name="datatype" use="required" type="xs:NCName"/>
      <xs:attribute name="name" use="required" type="xs:NCName"/>
      <xs:attribute name="show-docs">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="xml" />
            <xs:enumeration value="json" />
            <xs:enumeration value="xml json" />
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="acquire-from" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="formal-name" type="xs:string"/>
  <xs:element name="namespace"   type="xs:anyURI"/>
  <xs:element name="description">
    <xs:complexType mixed="true">
      <xs:choice maxOccurs="unbounded">
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="m:a"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="m:code"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="m:q"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="m:em"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="m:strong"/>
      </xs:choice>
    </xs:complexType>
  </xs:element>
  <xs:element name="remarks">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="m:p"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="title">
    <xs:complexType mixed="true">
      <xs:choice maxOccurs="unbounded">
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="m:code"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="m:q"/>
      </xs:choice>
    </xs:complexType>
  </xs:element>
  <xs:element name="schema-name">
    <xs:complexType mixed="true">
      <xs:choice maxOccurs="unbounded">
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="m:code"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="m:q"/>
      </xs:choice>
    </xs:complexType>
  </xs:element>
  <xs:element name="short-name">
    <xs:complexType mixed="true">
      <xs:choice maxOccurs="unbounded">
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="m:code"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="m:q"/>
      </xs:choice>
    </xs:complexType>
  </xs:element>
  <xs:element name="import">
    <xs:complexType mixed="true">
      <xs:attribute name="href" type="xs:anyURI" use="required"/>
      <xs:attribute name="name" type="xs:NCName" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="assembly">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" ref="m:description"/>
        <xs:element minOccurs="0" ref="m:remarks"/>
      </xs:sequence>
      <xs:attribute name="named" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="assemblies">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" ref="m:description"/>
        <xs:element minOccurs="0" ref="m:remarks"/>
      </xs:sequence>
      <xs:attribute name="address" type="xs:NCName"/>
      <xs:attribute name="group-as" use="required" type="xs:NCName"/>
      <xs:attribute name="named" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="field">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" ref="m:description"/>
        <xs:element minOccurs="0" ref="m:remarks"/>
      </xs:sequence>
      <xs:attribute name="named" use="required" type="xs:NCName"/>
      <xs:attribute name="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="fields">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" ref="m:description"/>
        <xs:element minOccurs="0" ref="m:remarks"/>
      </xs:sequence>
      <xs:attribute name="group-as" use="required" type="xs:NCName"/>
      <xs:attribute name="named" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="value">
    <xs:complexType mixed="true"/>
  </xs:element>
  <xs:element name="p">
    <xs:complexType mixed="true">
      <xs:choice maxOccurs="unbounded">
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="m:a"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="m:code"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="m:q"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="m:em"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="m:strong"/>
      </xs:choice>
    </xs:complexType>
  </xs:element>
  <xs:element name="a">
    <xs:complexType mixed="true">
      <xs:attribute name="href"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="q" type="xs:string"/>
  <xs:element name="code" type="xs:string"/>
  <xs:element name="em" type="xs:string"/>
  <xs:element name="strong" type="xs:string"/>
  <xs:element name="flag">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" ref="m:description"/>
        <xs:element minOccurs="0" ref="m:remarks"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="m:value"/>
      </xs:sequence>
      <xs:attribute name="datatype" type="xs:NCName"/>
      <xs:attribute name="name" use="required" type="xs:NCName"/>
      <xs:attribute name="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="choice">
    <xs:complexType>
      <xs:choice maxOccurs="unbounded">
        <xs:element ref="m:field"/>
        <xs:element ref="m:fields"/>
        <xs:element ref="m:assembly"/>
        <xs:element ref="m:assemblies"/>
      </xs:choice>
    </xs:complexType>
  </xs:element>
  <xs:element name="prose"/>
  <xs:element name="any"/>
  <xs:element name="example">
    <xs:complexType>
      <xs:sequence>
      <xs:element minOccurs="0" ref="m:description"/>
      <xs:element minOccurs="0" ref="m:remarks"/>
      <xs:choice minOccurs="0">
        <xs:any namespace="##other" processContents="lax"/>
      </xs:choice>
    </xs:sequence>
      <xs:attribute name="href" type="xs:anyURI"/>
      <xs:attribute name="path" type="xs:string"/>
      
      
    </xs:complexType>
  </xs:element>
  
</xs:schema>

=== anweiss/OSCAL/schema/demo/module-metaschema.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- OSCAL CATALOG METASCHEMA -->
<!-- validate with XSD and Schematron (linked) -->
<?xml-model href="../../build/metaschema/lib/metaschema-check.sch" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<?xml-stylesheet type="text/xsl" href="metaschema-browser.xsl"?>
<?xml-stylesheet type="text/css" href="../../build/metaschema/lib/metaschema-author.css"?>
<METASCHEMA xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://csrc.nist.gov/ns/oscal/metaschema/1.0 ../../build/metaschema/lib/metaschema.xsd"
 xmlns="http://csrc.nist.gov/ns/oscal/metaschema/1.0" top="acquired" use="acquired-model">

  <schema-name>FAKEUP Testing Schema</schema-name>
  <short-name>module</short-name>
  <namespace>urn:fakeup2</namespace>
  <remarks>
    <p>A test schema for prototyping and demonstrating the metaschema feature set.</p>
    
  </remarks>

  
  <define-field name="acquired-model" group-as="acquired" as="mixed" show-docs="xml json">
    <formal-name>Acquired Model</formal-name>
    <description>A string field, with mixed content</description>
    <remarks>
      <p>Defined in its own module!</p>
    </remarks>
    <example>
      <acquired-model  xmlns="urn:fakeup2">what's <em>up with this?</em></acquired-model>
    </example>
  </define-field>
    
</METASCHEMA>

=== anweiss/OSCAL/schema/demo/oscal-test-metaschema.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- OSCAL CATALOG METASCHEMA -->
<!-- validate with XSD and Schematron (linked) -->
<?xml-model href="../../build/metaschema/lib/metaschema-check.sch" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<?xml-stylesheet type="text/xsl" href="metaschema-browser.xsl"?>
<?xml-stylesheet type="text/css" href="../../build/metaschema/lib/metaschema-author.css"?>
<METASCHEMA xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://csrc.nist.gov/ns/oscal/metaschema/1.0 ../../build/metaschema/lib/metaschema.xsd"
 xmlns="http://csrc.nist.gov/ns/oscal/metaschema/1.0" top="kit-thing" use="kit">

  <schema-name>FAKEUP Testing Schema</schema-name>
  <short-name>oscal-test</short-name>
  <namespace>urn:fakeup</namespace>
  <remarks>
    <p>A test schema for prototyping and demonstrating the metaschema feature set.</p>
  </remarks>

  <import href="module-metaschema.xml" name="module"/>
  
  <define-assembly name="kit" group-as="thing-kit" show-docs="xml json">
    <flag name="id" datatype="ID" required="yes"/>
    <flag name="some_string" required="yes"/>
    <formal-name>Base</formal-name>
    <description>Wrapper for other stuff</description>
    <remarks>
      <p>The kit can have all kinds of Things.</p>
      <p>feature set for testing (schemas):
          enforcement of addressability constraints (distinctiveness of values)</p>
      <p>feature set for conversions: 'succinct JSON'; mapping nodes to element types in collapsed syntax.</p>
    <p>Also to do: find a case of variability in controls and show it off... parts?</p></remarks>
    <model>
      <assemblies named="thing" group-as="things"/>
    </model>    
    <example>
      <kit xmlns="urn:fakeup"
        some_string="string">
        <thing some_string="aha" id="thing001">
          <single-required-field>Required</single-required-field>
          <single-field/>
          <single-mixed-field>Mixed content? <i>here be content?</i></single-mixed-field>
        </thing>
      </kit>
    </example>
  </define-assembly>
  
  <define-assembly name="thing" group-as="things" show-docs="xml json">
    <flag name="id" datatype="ID" required="yes"/>
    <flag name="some_string" required="yes"/>
    <formal-name>Base</formal-name>
    <description>Wrapper for other stuff</description>
    <remarks>
      <p>A thing can be whatever: flags, fields of various sorts mixed and not, and assemblies.
        Also the various sorts of addressing should be demonstrated. The model described should be demonstrated in companion instances (XML and JSON), which can in turn be used as targets for mutual conversion.</p>
    </remarks>
    <model>
      <field named="single-required-field" required="yes"/>
      <field named="acquired-model"/>
      <field named="single-mixed-field" required="yes"  />
      <fields named="plural-field"       group-as="plurals"/>
      <fields named="plural-mixed-field" group-as="plurals-mixed"/>
      <assembly named="single-chunk"/>
      <assemblies named="chunk-among-chunks" group-as="chunks-together"/>
      <choice>
        <assembly named="vanilla"/>
        <assembly named="chocolate"/>
      </choice>
    </model>
  </define-assembly>
  
  <define-field name="single-required-field" as="string" show-docs="xml json">
    <formal-name>Single string (required)</formal-name>
    <description>As it says</description>
    <example href="base-example.xml" path="/descendant::single-required-field[1]">
      <!--<description>An example in a remote document</description>-->
    </example>
  </define-field>
  
  <define-field name="acquired-model" as="string" show-docs="xml json" acquire-from="module"/>
  
  <define-field name="single-mixed-field" as="mixed" show-docs="xml json">
    <formal-name>Single string but with mixed content</formal-name>
    <description>As it says</description>
  </define-field>
  
  <define-field name="plural-field" group-as="plurals" as="string" show-docs="xml json">
    <formal-name>A single occurrence of a plural (ha)</formal-name>
    <description>As it says</description>
  </define-field>
  
  <define-field name="plural-mixed-field" group-as="plurals-mixed" as="string" show-docs="xml json">
    <formal-name>Only one plural, but possibly mixed.</formal-name>
    <description>As it says</description>
  </define-field>
  
  <!--<define-field name="plural-flagged-mixed" group-as="plurals" as="string">
    <formal-name>Only one plural, but possibly mixed and possibly flagged.</formal-name>
    <description>As it says</description>
  </define-field>-->
  
  <define-assembly name="single-chunk" show-docs="xml json">
    <formal-name>Chunk</formal-name>
    <description>As it says</description>
    <model>
      <field named="single-required-field" required="yes"/>
      <prose/>
    </model>
  </define-assembly>
  
  <define-assembly name="chunk-among-chunks" show-docs="xml json">
    <formal-name>Chunk among chunks</formal-name>
    <description>As it says</description>
    <model>
      <field named="single-required-field" required="yes"/>
      <prose/>
    </model>
  </define-assembly>
  
  <define-assembly name="vanilla" show-docs="xml json">
    <formal-name>One Choice</formal-name>
    <description>As it says</description>
    <model>
      <field named="single-required-field" required="yes"/>
    </model>
  </define-assembly>
  
  <define-assembly name="chocolate" show-docs="xml json">
    <formal-name>Another Choice</formal-name>
    <description>As it says</description>
    <model>
      <field named="single-required-field" required="yes"/>
    </model>
  </define-assembly>
  
  <define-flag name="some_string" datatype="string" show-docs="xml json">
    <formal-name>A string flag</formal-name>
    <description>As it says</description>
  </define-flag>
  
  <define-flag name="id" datatype="ID" show-docs="xml json">
    <formal-name>An ID</formal-name>
    <description>As it says</description>
  </define-flag>
  
  <!--<define-flag name="">
    <formal-name>A string flag</formal-name>
    <description>As it says</description>
  </define-flag>
  <define-flag name="some_string"/>
  -->
  
</METASCHEMA>

=== anweiss/OSCAL/schema/demo/baby-metaschema.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- OSCAL CATALOG METASCHEMA -->
<!-- validate with XSD and Schematron (linked) -->
<!--<?xml-model href="../../build/metaschema/lib/metaschema-check.sch" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>-->
<?xml-stylesheet type="text/xsl" href="metaschema-browser.xsl"?>
<?xml-stylesheet type="text/css" href="../../build/metaschema/lib/metaschema-author.css"?>
<METASCHEMA xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://csrc.nist.gov/ns/oscal/metaschema/1.0 ../../build/metaschema/lib/metaschema.xsd"
 xmlns="http://csrc.nist.gov/ns/oscal/metaschema/1.0" root="baby">
  
  <schema-name>Baby TestingSchema</schema-name>
  <short-name>Baby</short-name>
  <namespace>urn:baby</namespace>
  
  <import href="module-metaschema.xml"/>
  <define-assembly name="baby" group-as="babies">
    <formal-name>Baby</formal-name>
    <description>Testing</description>
    <model>
      <fields named="toy"/>
      <field named="acquired-field" required="yes"/>
      <assemblies named="baby"></assemblies>
    </model>    
  </define-assembly>

<define-field name="toy" group-as="toybox">
  <formal-name>Toy</formal-name>
  <description>A typical toy</description>
</define-field>
  
</METASCHEMA>
